In [1]:
# CREATING NUMPY ARRAY
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
print(arr)
 
# Creating a rank 2 Array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
 
# Creating an array from tuple
arr = np.array((1, 3, 2))
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


In [2]:
# ACCESSING ARRAY INDEX
import numpy as np
 
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Printing a range of Array
# with the use of slicing method
arr2 = arr[:2, ::2]
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [3]:
# Printing elements at
# specific Indices
arr3 = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)


Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [4]:
# BASIC ARRAY OPERATIONS
import numpy as np
 
# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [5]:
# MATH OPERATIONS ON DATA TYPE ARRAY
import numpy as np
 
# First Array
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)
print(Sum)
 
# Addition of all Array elements
Sum1 = np.sum(arr1)
print(Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print(Sqrt)
 
# Transpose of Array
Trans_arr = arr1.T
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


In [6]:
# BASIC SLICING AND INDEXING
import numpy as np  
a = np.arange(20)

print("a[15] =", a[15])
print("a[-8:17:1] =", a[-8:17:1])
print("a[10:] =", a[10:])

a[15] = 15
a[-8:17:1] = [12 13 14 15 16]
a[10:] = [10 11 12 13 14 15 16 17 18 19]


In [7]:
# ADVANCED INDEXING
import numpy as np
a = np.array( [[1, 2], [3, 4], [5, 6]] )
print( a[[0, 1, 2], [0, 0, 1]] )

[1 3 6]


In [8]:
# MATRIX OPERATIONS IN NUMPY
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Addition:\n", np.add(x, y))
print("Subtraction:\n", np.subtract(x, y))
print("Division:\n", np.divide(x, y))

Addition:
 [[ 8 10]
 [13 15]]
Subtraction:
 [[-6 -6]
 [-5 -5]]
Division:
 [[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [9]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Element-wise multiplication:\n", np.multiply(x, y))
print("Matrix multiplication:\n", np.dot(x, y))

Element-wise multiplication:
 [[ 7 16]
 [36 50]]
Matrix multiplication:
 [[25 28]
 [73 82]]


In [10]:
import numpy as np

x = np.array([[1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print("Square root:\n", np.sqrt(x))
print("Sum of all elements:", np.sum(y))

print("Column-wise sum:", np.sum(y, axis=0))
print("Row-wise sum:", np.sum(y, axis=1))
print("Transpose:\n", x.T)

Square root:
 [[1.         1.41421356]
 [2.         2.23606798]]
Sum of all elements: 34
Column-wise sum: [16 18]
Row-wise sum: [15 19]
Transpose:
 [[1 4]
 [2 5]]


In [11]:
#creating numpy array
# 1.using np.array
import numpy as np
a1 = np.array([1,2,3,4,5,6,7,8])
a2 = np.array([[1,2],[3,4],[5,6],[7,8]])
a3 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(a1)
print(a2)
print(a3)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [12]:
#2.using numpy factors
import numpy as np
c1 = np.zeros((3,3))
c2 = np.ones((5,5))

print(c1)
print(c2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
#array indexing 
import numpy as np
print(a1[2])
print(a1[-1])
print(a2[1][0])
print(a2[1][1])
print(a3[0][0][0])

3
8
3
4
1


In [14]:
#cheecking data tyoes
import numpy as np
print(type(a1))

<class 'numpy.ndarray'>


In [15]:
#parameter of array
'''1.Axis -> describe order of indexing array
Axis 0 -> One Dimensional
Axis 1 -> Two Dimensional
Axis 2 -> Three Dimensional
'''

'1.Axis -> describe order of indexing array\nAxis 0 -> One Dimensional\nAxis 1 -> Two Dimensional\nAxis 2 -> Three Dimensional\n'

In [16]:
#2.Shape -> No of elements along each array
import numpy as np
print(a1.shape)
print(a2.shape)
print(a3.shape)

(8,)
(4, 2)
(1, 4, 2)


In [17]:
#numpy Arithmetic operator
import numpy as np
X = np.array([1,2,3])
Y = np.array([4,5,6])
print(X)
print(Y)
print(X-Y)
print(X+Y)
print(X*Y)
print(X/Y)

[1 2 3]
[4 5 6]
[-3 -3 -3]
[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [18]:
#Unary operators
import numpy as np
Z = np.array([-3,-2,-1,0,1,2,3])
print(np.absolute(Z))

[3 2 1 0 1 2 3]


In [19]:
#Binary operation
import numpy as np
res = np.add(X,Y)
print(res)

[5 7 9]


In [20]:
#Mathematical functions
import numpy as np
a = np.array([0, np.pi/2, np.pi])
print(a)
#print(sin(a))
b = np.array([0,1,2,3,4,5])
print(b)
print(np.exp(b))
print(np.sqrt(b))

[0.         1.57079633 3.14159265]
[0 1 2 3 4 5]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
[0.         1.         1.41421356 1.73205081 2.         2.23606798]


In [21]:
#Statistical  Functions
import numpy as np
data = np.array([10,20,330,40,50])
print(data)
print(np.sum(data))
print(np.mean(data))
print(np.median(data))
print(np.var(data))
print(np.min(data))
print(np.max(data))

[ 10  20 330  40  50]
450
90.0
40.0
14600.0
10
330
